image: node:10

cache:
  paths:
  - node_modules/

before_script:
  - yarn install

stages:
  - test
  - deploy

jest_tests:
  stage: test
  script:
    - yarn test

pages:
  image: node:latest
  stage: deploy
  script:
    - yarn build
    - mv public public-vue
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
